services:
  recipe-scraper:
    build:
      context: .
      dockerfile: scraper.Dockerfile
    restart: unless-stopped
    environment:
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_REDIS_URL=redis://redis:6379/0
      - CACHE_REDIS_DB=0
      - CACHE_KEY_PREFIX=mmeals_
    depends_on:
      - redis
    ports:
      - 8002:8000
