services:
  manage-meals-web:
    image: ghcr.io/managemeals/manage-meals-web:latest
    restart: unless-stopped
    environment:
      PUBLIC_MAIN_TITLE: ManageMeals
      PASSWORD_MIN_LENGTH: 6
      API_URL: http://manage-meals-api:3000/v1
      COOKIE_ACCESS_TOKEN: mmeals_access_token
      COOKIE_REFRESH_TOKEN: mmeals_refresh_token
      COOKIE_ACCESS_TOKEN_EXPIRE_SEC: 600
      COOKIE_REFRESH_TOKEN_EXPIRE_SEC: 2629746
      ORIGIN: http://localhost:3001
      BODY_SIZE_LIMIT: Infinity
